#!/bin/sh
# Mock yarn v2
echo "yarn $@" >> pm.log
mkdir -p node_modules
# Simulate updating package.json by appending the dependency.
PKG_PATH=$2
PKG_NAME=$(basename "$PKG_PATH")
echo ",\"$PKG_NAME\":\"file:$PKG_PATH\"" >> package.json
exit 0
